# Base settings
timezone: Europe/Kiev
encoding: utf-8
highlighter: pygments

# Site settings
title:       Dev notes
email:
author:      Dmitry Maslov
description: "Some"
baseurl:     ""
url:         "http://dmaslov.github.io"

# Google analytics
google_analytics: UA-61201089-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

#Navigation
show_nav_block: true
show_approx_read: false

# Social icons
show_social_icons: true
github_username: dmaslov
stackoverflow_id:
twitter_username: lazzy_panda
google_plus_id:
linkedin_id: 240600758
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:title
paginate:     5
sass:
  compressed: true
